spring:
  application:
    name: springbootproj2

  datasource:
    url: jdbc:postgresql://localhost:5432/server
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql=true:

car:
  enabled-fields: brand,year
  max: 2

